version: '3.7'

services:
  web:
    build: ./VideoStreaming
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./VideoStreaming/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev