# Generated by Django 2.1.7 on 2020-05-13 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('channel_name', models.CharField(max_length=50)),
                ('channel_id', models.CharField(default='VUSQh9N', max_length=25, unique=True)),
                ('channel_dp', models.ImageField(default='/home/karan/Documents/projects/video_streaming/VideoStreaming/staticdefaults/channel_dp.jpg', upload_to='channel_dp')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Channel',
            },
        ),
    ]
