# Generated by Django 2.1.7 on 2020-05-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channels', '0004_auto_20200516_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(default='fL1qESa', max_length=25, unique=True),
        ),
    ]
