# Generated by Django 2.1.7 on 2020-05-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channels', '0005_auto_20200516_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(default='ifNIPJg', max_length=25, unique=True),
        ),
    ]
