# Generated by Django 2.1.7 on 2020-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channels', '0007_auto_20200519_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(default='ufX5vFs', max_length=25, unique=True),
        ),
    ]
