# Generated by Django 2.1.7 on 2020-05-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channels', '0008_auto_20200520_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
