# Generated by Django 2.1.7 on 2020-05-19 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Channels', '0007_auto_20200519_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('video_title', models.CharField(max_length=50)),
                ('video_desc', models.TextField()),
                ('video_id', models.CharField(default='8tyY7tx88e', max_length=50, unique=True)),
                ('video_thumbnail', models.ImageField(default='/home/karan/Documents/projects/video_streaming/VideoStreaming/staticdefaults/video_thumbnail.png', upload_to='video_thumbnail')),
                ('video', models.FileField(upload_to='videos')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Channels.Channel')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Video',
            },
        ),
    ]
