# Generated by Django 2.1.7 on 2020-05-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0002_auto_20200520_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
