# Generated by Django 3.0.6 on 2020-05-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0003_auto_20200521_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(default='defaults/video_thumbnail.jpg', upload_to='video_thumbnail'),
        ),
    ]
