# Generated by Django 2.1.7 on 2020-05-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAcc', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
