# Generated by Django 2.1.7 on 2020-05-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAcc', '0004_auto_20200516_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='/defaults/profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
