# Generated by Django 2.1.7 on 2020-05-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAcc', '0005_auto_20200516_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='/defaults/profile_pic.png', upload_to='profile_pics'),
        ),
    ]
