# Generated by Django 3.0.6 on 2020-05-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAcc', '0007_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='defaults/profile_pic.png', upload_to='profile_pics'),
        ),
    ]
